//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.14 at 12:42:00 PM CEST 
//


package com.github.rshtishi.bankws.soap.client.bankws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.rshtishi.bankws.soap.client.bankws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTrasactions_QNAME = new QName("http://service.bankws.rshtishi.github.com/", "getTrasactions");
    private final static QName _GetTrasactionsForClient_QNAME = new QName("http://service.bankws.rshtishi.github.com/", "getTrasactionsForClient");
    private final static QName _GetTrasactionsForClientResponse_QNAME = new QName("http://service.bankws.rshtishi.github.com/", "getTrasactionsForClientResponse");
    private final static QName _GetTrasactionsResponse_QNAME = new QName("http://service.bankws.rshtishi.github.com/", "getTrasactionsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.rshtishi.bankws.soap.client.bankws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTrasactions }
     * 
     */
    public GetTrasactions createGetTrasactions() {
        return new GetTrasactions();
    }

    /**
     * Create an instance of {@link GetTrasactionsForClient }
     * 
     */
    public GetTrasactionsForClient createGetTrasactionsForClient() {
        return new GetTrasactionsForClient();
    }

    /**
     * Create an instance of {@link GetTrasactionsForClientResponse }
     * 
     */
    public GetTrasactionsForClientResponse createGetTrasactionsForClientResponse() {
        return new GetTrasactionsForClientResponse();
    }

    /**
     * Create an instance of {@link GetTrasactionsResponse }
     * 
     */
    public GetTrasactionsResponse createGetTrasactionsResponse() {
        return new GetTrasactionsResponse();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link LocalDateTime }
     * 
     */
    public LocalDateTime createLocalDateTime() {
        return new LocalDateTime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTrasactions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.bankws.rshtishi.github.com/", name = "getTrasactions")
    public JAXBElement<GetTrasactions> createGetTrasactions(GetTrasactions value) {
        return new JAXBElement<GetTrasactions>(_GetTrasactions_QNAME, GetTrasactions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTrasactionsForClient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.bankws.rshtishi.github.com/", name = "getTrasactionsForClient")
    public JAXBElement<GetTrasactionsForClient> createGetTrasactionsForClient(GetTrasactionsForClient value) {
        return new JAXBElement<GetTrasactionsForClient>(_GetTrasactionsForClient_QNAME, GetTrasactionsForClient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTrasactionsForClientResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.bankws.rshtishi.github.com/", name = "getTrasactionsForClientResponse")
    public JAXBElement<GetTrasactionsForClientResponse> createGetTrasactionsForClientResponse(GetTrasactionsForClientResponse value) {
        return new JAXBElement<GetTrasactionsForClientResponse>(_GetTrasactionsForClientResponse_QNAME, GetTrasactionsForClientResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTrasactionsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.bankws.rshtishi.github.com/", name = "getTrasactionsResponse")
    public JAXBElement<GetTrasactionsResponse> createGetTrasactionsResponse(GetTrasactionsResponse value) {
        return new JAXBElement<GetTrasactionsResponse>(_GetTrasactionsResponse_QNAME, GetTrasactionsResponse.class, null, value);
    }

}
